wandb_version: 1

entries:
  desc: null
  value:
    exp_name: ex1
    seed: 1
    env_name: CartPole-v1
    max_episode_steps: 100
    train_episodes: 500
    batch_size: 64
    min_update_samples: 2000
    testing: false
    model_path: default
    save_video: true
    save_model: true
    save_logging: true
    silent: false
    use_wandb: true
    run_suffix: 0
exp_name:
  desc: null
  value: ex1
seed:
  desc: null
  value: 1
env_name:
  desc: null
  value: CartPole-v1
max_episode_steps:
  desc: null
  value: 100
train_episodes:
  desc: null
  value: 500
batch_size:
  desc: null
  value: 64
min_update_samples:
  desc: null
  value: 2000
testing:
  desc: null
  value: false
model_path:
  desc: null
  value: default
save_video:
  desc: null
  value: true
save_model:
  desc: null
  value: true
save_logging:
  desc: null
  value: true
silent:
  desc: null
  value: false
use_wandb:
  desc: null
  value: true
run_suffix:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1694683743.005617
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 55
      - 105
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.15.9
      8:
      - 1
      - 5
